Post-review fixes
nrydanov/bison-flex-calculator pull request #24
Opened 2022-04-19 19:54 UTC by nrydanov

2022-04-19 20:05 UTC, hnarkaytis requested changes

2022-04-19 20:05 UTC, hnarkaytis commented on src/ast_calc.c
> +  abstract_expr_calc->result = ast_eval (extra);
тут как-то нет шанса вернуть не SUCCESS, так зачем тогда возвращать статус? Пусть возвращается значение.

2022-04-19 20:05 UTC, hnarkaytis commented on src/jit_calc.c
>    double (*f)(int) = (double (*)(int)) LLVMGetFunctionAddress (engine, "func");
Не понял почему функция принимает int. Мы ее без аргументов делаем. Я бы ожидал double (*f) (void)

2022-04-20 08:35 UTC, nrydanov commented on src/jit_calc.c
>    double (*f)(int) = (double (*)(int)) LLVMGetFunctionAddress (engine, "func");
Я добавил на случай, если это позже пригодится. Как я понимаю, если вдруг придется дописывать логику с вычислением выражения с x-ом внутри, то этот аргумент пригодится. В целом, могу на данном этапе удалить.

2022-04-20 08:35 UTC, nrydanov commented on src/abstract_calc.h
> +  int (*calc) (struct abstract_expr_calc_t* );
Я результат кладу в отдельное поле внутри абстрактного калькулятора. Тогда можно везде возвращать статус без проблем.

2022-04-20 09:11 UTC, hnarkaytis commented
Надо почистить типы. аргумент у функции int, вычисления в long double, возвращаемое значение double.

2022-04-20 09:11 UTC, closed without merging